"""Board

Revision ID: 9260fb8fcdce
Revises: eef1851eca0d
Create Date: 2023-09-23 18:24:10.325832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from litestar.contrib.sqlalchemy.types import DateTimeUTC

# revision identifiers, used by Alembic.
revision: str = '9260fb8fcdce'
down_revision: Union[str, None] = 'eef1851eca0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project'))
    )
    op.create_table('task',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('project_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_task_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('project')
    # ### end Alembic commands ###
